### ISSUE TITLE
"Login: User required to be logged in" error

### ISSUE THREAD

**Issue by magicman-dot** [misiektoja/lastfm_monitor#1]
I'm getting this error when I try to run the app:

_"Login: User required to be logged in"_

I have proper APi key and secret defined. Any ideas ?

**Comment by misiektoja** [comment]
Hey, change your privacy settings and disable 'Hide recent listening information':

![8374_300f697b535d761201ee64be793761f6180b5db010b1144579f48f466e4e0967](https://github.com/misiektoja/lastfm_monitor/assets/55950820/f1ff12f0-fb78-4821-b183-3e28584b883a)

This error message comes from pyLast and is not too descriptive. I will add some info about it to the README.

**Comment by magicman-dot** [comment]
Thanks it works now !
